### PR TITLE
refactor: use forEach

### PR DESCRIPTION
**Pull request by escapedcat**
Tiny refactor. Related tests are passing locally.

### CODE REVIEW

**Comment by fiatjaf** [comment]
But why?

**Comment by escapedcat** [comment]
Got it. Yeah, was just relying on the test there.

**Comment by fiatjaf** [comment]
You would need 100% coverage before you could do that safely.

**Comment by escapedcat** [comment]
Would you take a PR to cover the returns?

**Comment by fiatjaf** [comment]
No, please, leave it like it is.

**Pull request closed without merging**
