### PR TITLE
fix failing test cases

### PR DESCRIPTION
**Pull request by sepehr-safari**
- replaced relay addresses with `nos.lol` and fixed failing test cases

### CODE REVIEW

**Comment by fiatjaf** [comment]
The tests are flaky because relying on external relays for them is wrong, but they often work. Changing here won't help as they will eventually fail with nos.lol too.

A better approach could be to run the tests inside a docker thing that also spins up a nostr-rs-relay or something and then uses that. I don't know, I don't think it's that important.

**Comment by sepehr-safari** [comment]
they won't fail with `nos.lol`.
by the way, I'm trying to implement mock websocket. will send a PR once it's ready.

**Comment by fiatjaf** [comment]
Why won't they fail with nos.lol?

**Comment by sepehr-safari** [comment]
I tested and it passed. it's about the response time of the relay. `nos.lol` is fast enough to pass the tests in our desired time.

**Pull request closed without merging**
