### PR TITLE
nip19: remove note1.

### PR DESCRIPTION
**Pull request by AsaiToshiya**
Related: https://github.com/nostr-protocol/nips/pull/1586

### CODE REVIEW

**Comment by eskema** [comment]
this feels very wrong to me

**Comment by fiatjaf** [comment]
Why?

**Comment by eskema** [comment]
because the decode function is still needed to read all the past content that is already out there, and there are probably a lot of code that depends on this functions existing to continue working. (at least mine does) It’s one thing to have clients phase it out, but it’s another to just break things in clients that still use it

**Comment by fiatjaf** [comment]
He is right, @AsaiToshiya.

**Comment by AsaiToshiya** [comment]
What about encoding? Is it necessary?

This PR is just a suggestion and I don't mind if you revert changes.

**Comment by fiatjaf** [comment]
Encoding we should remove.

**Comment by AsaiToshiya** [comment]
Ok, I'll open another PR.

**Comment by eskema** [comment]
I use note1 encoding for note ids since we moved out of showing hex strings to users a long long time ago, nevent and naddr cannot be used for such which leaves me with no other option than reverting back to hex strings. fun

**Comment by fiatjaf** [comment]
Why can't you use `nevent`? Of course you can and should!

**Pull request merged**
