### PR TITLE
export nip17

### PR DESCRIPTION
**Pull request by Egge21M**
Added nip17 export to index.ts for bundlers that do not support `exports` yet

### CODE REVIEW

**Comment by fiatjaf** [comment]
Just out of curiosity, what are these bundlers?

**Comment by Egge21M** [comment]
> Just out of curiosity, what are these bundlers?

While supported in react-native / metro, it's a real pain to make it work and is very likely to break other stuff

**Comment by fiatjaf** [comment]
OK, I'm going to merge this, but I wanted to actually go the other way because there are way too many people using this index file without knowing.

Maybe I'll release a v3 soon that gets rid of the index file altogether and makes other changes.

**Comment by Egge21M** [comment]
> OK, I'm going to merge this, but I wanted to actually go the other way because there are way too many people using this index file without knowing better.

Thanks!

I see your point, but isn't that on them? By getting rid of the main entry file, you will loose backwards compatibility and force bundler updates and settings on consumers. Keeping both lets people opt-in to better tree shaking. If they don't they either can't or... skill issues.

Also you need the index files anyways for standalone bundles, no?

**Pull request merged**
