### PR TITLE
including nostr specialized types

### PR DESCRIPTION
**Pull request by antonioconselheiro**
exporting nip19 nostr specific types, implements: https://github.com/nbd-wtf/nostr-tools/issues/408

### CODE REVIEW

**Comment by fiatjaf** [comment]
Is this ready to merge?

**Comment by antonioconselheiro** [comment]
In my view yes, but I'm nobody.
In nip49.ts file there is a check for ncryptsec using regex, it can be replaced by guard type included in core.ts, would it be good to replace it to avoid repeating equivalent code?

**Comment by fiatjaf** [comment]
Yes, except the types should be called "npub" not "npublic", "nsec" not "nsecret", but I can fix that after I merge.

**Comment by antonioconselheiro** [comment]
so, maybe `nadress` should be just `nadrr`

**Comment by fiatjaf** [comment]
I'll take a look at this soon, if I don't forget. Thank you.

**Comment by antonioconselheiro** [comment]
Thank you for Nostr sir,
but talking about types exportations,
can this lib export too the { write: boolean, read: boolean } relay config interface with a name?
If yes, I'll include in this pull request

**Comment by fiatjaf** [comment]
It does hurt my ability to understand my own library.

**Comment by alexgleason** [comment]
Naming types is overrated. It's better to just copy the same type in multiple places, unless it's a truly universal interface.

**Comment by antonioconselheiro** [comment]
ok

**Comment by antonioconselheiro** [comment]
Another thing...
There is already a regex to valid nip05 and would be nice include type guard for this too,
NIP05 type is included in this PR but not the type guard, but to include this it will be in nip5.ts and not with the others in `NostrTypeGuard` object in `core.ts`.

Make sense include this in nip5.ts?

```typescript
export const isNip05 = (value?: string | null): value is Nip05 => NIP05_REGEX.test(value || '')
```

**Comment by fiatjaf** [comment]
Yes. In nip.ts

**Comment by antonioconselheiro** [comment]
`NIP05_REGEX` matches for `domain.com` and `name@domain.com`, but my type in this PR for NIP05 is `${string}@${string}`, is my type right? or should have a regex with @ as mandatory to validate?

**Comment by alexgleason** [comment]
NIP05_REGEX is wrong, I learned after looking at NIP-05 itself. It's too lenient. I was following what the person had done before, but the `@` is actually required by the spec.

Btw I think this is still a pointless type.

**Comment by antonioconselheiro** [comment]
Thank you, but I can't see they as pointless types, I see a lot of value in this.

**Comment by antonioconselheiro** [comment]
This unit test requires `NIP05_REGEX` to include @ as optional 🤔, is this wrong? Or is this a peculiarity for the method `queryProfile`?
image

**Comment by antonioconselheiro** [comment]
[nrelay got deprecated](https://github.com/nostr-protocol/nips/commit/ecee40df), so I should remove nrelay from this pr, right?

**Comment by antonioconselheiro** [comment]
you just merged it, but I found a problem in isNcryptsec guard, it is returning 'is Note' instead 😳😥

**Pull request merged**
