### PR TITLE
+nip98.unpackEventFromToken +nip98.validateEvent

### PR DESCRIPTION
**Pull request by Airtune**

### CODE REVIEW

**Review by alexgleason — APPROVED** [review]
Beautiful diff. 

cc @Dolu89

**Review by Dolu89 — CHANGES_REQUESTED** [review]
Can you please update the example? It's an error from me, it should be like this
```
await nip98.getToken('https://example.com/login', 'post', (e) =>sign(e), true);
```

**Comment by Airtune** [comment]
> Can you please update the example? It's an error from me, it should be like this
> 
> ```
> await nip98.getToken('https://example.com/login', 'post', (e) => sign(e), true);
> ```
> 
> EDIT: on file nip98.ts line 23

I updated the example and also updated the example for validation on line 63:

```
await nip98.validateToken('Nostr base64token', 'https://example.com/login', 'post')
```

**Review by Dolu89 — APPROVED** [review]
Nice update

**Pull request merged**
