### PR TITLE
Making AbstractSimplesPool more extensible

### PR DESCRIPTION
**Pull request by antonioconselheiro**
I wanna extends AbstractSimplesPool to create and test other complementary implementations for my software, It will be so bad to change this to `protected`? Please 🙏

### CODE REVIEW

**Comment by fiatjaf** [comment]
I didn't even know this was a thing. Apparently JavaScript is Java now.

**Comment by antonioconselheiro** [comment]
javascript still a wild jungle, typescript is the civilization

**Comment by fiatjaf** [comment]
TypeScript and JavaScript are the same thing.

**Comment by antonioconselheiro** [comment]
I disagree, javascript drove me crazy, but typescript was very good for my mental health

**Pull request merged**
