### PR TITLE
devcontainer config

### PR DESCRIPTION
**Pull request by antonioconselheiro**
With [devcontainer](https://containers.dev/) is possible to start the project into a [vscode](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers) or intellij without install any dev dependency in our host, neither node nor typescript.

I've created a devcontainer config for this library with `just` and `bun`,
is a customized environment for this library development, running tests and local build,
I hope you find it useful.

just included

### CODE REVIEW

**Comment by fiatjaf** [comment]
Jesus Christ, what are they doing with programmers?

**Comment by fiatjaf** [comment]
I'll merge this, but I reserve my right to nuke it out of existence if I wake up in a bad mood.

**Comment by fiatjaf** [comment]
Thank you.

**Comment by antonioconselheiro** [comment]
It would be very bad to have to controll different versions and dependencies installed on my host notebook (and install stuff into my host machine scares me a little), but surely is in your authority to nuke out of existence anything inside your library.

Thank you for receiving these settings.

**Comment by antonioconselheiro** [comment]
See this example if you find it interesting, I've created a devcontainer with ```nak``` and ```jq``` for my nostr client dev environment:

https://github.com/antonioconselheiro/bitcoin-nostred-auction/blob/master/.devcontainer/Dockerfile

Maybe you find this usefull.

**Pull request merged**
